language: php

php:
  - 5.6
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --dev

script:
  - mkdir -p build/logs
  - vendor/phpunit/phpunit/phpunit -c phpunit.xml --verbose
